version: "3.8"

services:
  app: &services_app
    build: .
    user: root
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
      - 8089:8089
      - 8090:8090
# this
    depends_on:
      - db
      - solr
    configs:
      - source: config.rb
        target: /opt/app/config/config.rb
      - source: en.yml
        target: /opt/app/plugins/local/public/locales/en.yml
    secrets:
      # @note Customize these in your local .env file if necessary
      - APPCONFIG_DB_URL
    environment:
      # @note ArchivesSpace settings can be specified by setting ENV vars of the form
      #       APPCONFIG_<Upcased Parameter Name>. We have run into problems with any
      #       that require parsing JSON, however, so avoid that.
      APPCONFIG_PLUGINS_OVERRIDE: local,lcnaf,digitization_work_order
      APPCONFIG_SOLR_URL: http://solr:8983/solr/archivesspace
      JAVA_OPTS: "-Djava.awt.headless=true -Dfile.encoding=UTF-8 -server -Xss512k -Djavax.accessibility.assistive_technologies=''"
    volumes:
      - aspace_data:/opt/app/data
      - solr_data:/var/solr/data:ro
  
  updater:
    <<: *services_app
    command: scripts/setup-database.sh
    ports: []
    restart: on-failure
  
  solr:
    image: solr:8.11.2
    environment:
      # Eliminates "failed to reserve shared memory" warning
      # @see https://support.pingidentity.com/s/article/Addressing-Failed-to-reserve-shared-memory-errors
      GC_TUNE: -XX:-UseLargePages
    ports:
      - 8983:8983
    command: solr-precreate archivesspace /opt/solr-8.10.0/server/solr/configsets/archivesspace
    volumes:
      - ./solr:/opt/solr-8.10.0/server/solr/configsets/archivesspace/conf:ro
      - solr_data:/var/solr/data
  
  db:
    image: mariadb:10.9
    environment:
      # @note These are all hardcoded for convenience
      MYSQL_ROOT_PASSWORD: archivesspace-root
      MYSQL_DATABASE: archivesspace
      MYSQL_USER: archivesspace
      MYSQL_PASSWORD: archivesspace
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

configs:
  config.rb:
    file: config/config.rb
  en.yml:
    file: config/en.yml

secrets:
  APPCONFIG_DB_URL:
    environment: APPCONFIG_DB_URL

volumes:
  aspace_data: {}
  db_data: {}
  solr_data: {}
