name: Docker Image CI

on:
  push:
    branches: [ "main" ]
 
jobs:

  build_and_publish:
   
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    
    - uses: actions/checkout@v3
    - name: Build and publish the Docker image
      uses: VaultVulp/gp-docker-action@1.1.12
      with: 
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        image-name: berkeleylibrary/archivesspace
        build-context: ./   
     

